### ISSUE TITLE
Error message with time-at-risk boundaries incorrect

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/SelfControlledCohort#1]
Currrently runSelfControlledCohort will stop if riskWindowStartExposed < riskWindowEndExposed:  https://github.com/OHDSI/SelfControlledCohort/blob/master/R/SelfControlledCohort.R#L168

However, if addLengthOfExposureExposed = TRUE, then this stopping condition should not be satisfied.

**Comment by schuemie** [comment]
Should be fixed in latest release. See this commit: https://github.com/OHDSI/SelfControlledCohort/commit/d09693e1e5a551e0b5600bf301c7cce1bfdc1a49#diff-80d6335bf64f0643962ddb304a1d8258L168
