### ISSUE TITLE
Add vignette that describes the method in detail with examples

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SelfControlledCohort#6]
I'm thinking of writing a vignette that describes this method in detail with examples for anyone not familiar with it. @schuemie, what do you think?

**Comment by schuemie** [comment]
That would we great! Please go ahead.

**Comment by ablack3** [comment]
@schuemie, Does SelfControledCohort allow for running an analysis on a specific cohort? It looks to me like the user can only specify the exposure and outcome concept ids and must run the analysis on all patients in their CDM with possible restrictions on age and dates. Is there a reason why we don't provide the option to subset the analysis to a specific cohort of patients?

i.e. Add something like this to the SQL that creates the risk windows
`{!is.null(@cohortId)} ? {INNER JOIN @cdm_results_schema.cohort ch ON t1.person_id = ch.subject_id WHERE ch.cohort_id = @cohortId`}

**Comment by schuemie** [comment]
Like all the other methods in HADES, the exposures and outcomes can be specified as concept IDs (when `exposureTable = "drug_era"` and `outcomeTable = "condition_era"`), or as cohort definition IDs (when `exposureTable` and `outcomeTable` are set to something else). So if the user wants to restrict the analysis to a specific subpopulation, the way to do that would be by adding inclusion criteria to the exposure cohorts.

**Comment by ablack3** [comment]
Thanks for your help @schuemie. As part of the vignette I would like to develop a couple minimal examples to demonstrate the method. These examples could also be used as part of testing. A small example that can run entirely in R is preferable since an external CDM might not always be available.  I tried running a minimal example using Andromeda. which technically worked quite well but did not produce the result I expected. I think the reason is that the SQLite translation for date logic is not correct, or at least not giving the results I would expect. Here is a reprex demonstrating the issues I found. My expectations are expressed with calls to `testthat::expect_equal()`.

``` r
library(Andromeda)
library(SqlRender)
library(DatabaseConnector)

andro <- andromeda(data = data.frame(date1 = as.Date("2020-01-01"), date2 = as.Date("2020-01-02")))
con <- connect(dbms = "sqlite", server = andro@dbname)
#> Connecting using SQLite driver
andro$data
#> # Source:   table<data> [?? x 2]
#> # Database: sqlite 3.33.0
#> #   [C:\Users\ADAMBL~1\AppData\Local\Temp\RtmpgH9pk6\file2ce08683fd8.sqlite]
#>   date1 date2
#>   <dbl> <dbl>
#> 1 18262 18263

(result <- dbGetQuery(con, translate("select date1, date2, DATEDIFF(DAY, date1, date2) as datediff from data;", "sqlite")))
#>   date1 date2     datediff
#> 1 18262 18263 1.157401e-05
testthat::expect_equal(result$datediff, 1)
#> Error: result$datediff not equal to 1.
#> 1/1 mismatches
#> [1] 1.16e-05 - 1 == -1


(result <- dbGetQuery(con, translate("select date1, date2, DATEADD(DAY, 1, date1) as one_day_later from data;", "sqlite")))
#>   date1 date2 one_day_later
#> 1 18262 18263        104662
testthat::expect_equal(result$date2, result$one_day_later)
#> Error: result$date2 not equal to result$one_day_later.
#> 1/1 mismatches
#> [1] 18263 - 104662 == -86399

(result <- dbGetQuery(con, translate("select DATEDIFF(DAY, date1, DATEADD(DAY, 1, date1)) as should_be_1_day from data;", "sqlite")))
#>   should_be_1_day
#> 1               1
testthat::expect_equal(result$should_be_1_day, 1) # this test passes

translate("DATEDIFF(DAY, date1, date2)", "sqlite")
#> [1] "JULIANDAY(date2, 'unixepoch') - JULIANDAY(date1, 'unixepoch')"
translate("DATEADD(DAY, 1, date1)", "sqlite")
#> [1] "CAST(STRFTIME('%s', DATETIME(date1, 'unixepoch', (1)||' days')) AS REAL)"

dbGetQuery(con, "
select date1, date2,
  JULIANDAY(date2),
  JULIANDAY(date1),
  JULIANDAY(date2) - JULIANDAY(date1),
  JULIANDAY(date1, 'unixepoch'),
  JULIANDAY(date2, 'unixepoch'),
  JULIANDAY(date2, 'unixepoch') - JULIANDAY(date1, 'unixepoch')
from data") %>%
  tidyr::gather("SQL", "value")
#>                                                             SQL        value
#> 1                                                         date1 1.826200e+04
#> 2                                                         date2 1.826300e+04
#> 3                                              JULIANDAY(date2) 1.826300e+04
#> 4                                              JULIANDAY(date1) 1.826200e+04
#> 5                           JULIANDAY(date2) - JULIANDAY(date1) 1.000000e+00
#> 6                                 JULIANDAY(date1, 'unixepoch') 2.440588e+06
#> 7                                 JULIANDAY(date2, 'unixepoch') 2.440588e+06
#> 8 JULIANDAY(date2, 'unixepoch') - JULIANDAY(date1, 'unixepoch') 1.157401e-05
```

<sup>Created on 2020-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is there a reason that the ['unixepoch' modifier ](https://sqlite.org/lang_datefunc.html)is used in the translation of DATEDIFF and DATEADD (i.e. using seconds as the unit instead of days)?

**Comment by schuemie** [comment]
DatabaseConnector and SqlRender have extensive support of SQLite. Why use Andromeda (which just happens to use RSQLite as a backend)? 

I recommend using [Eunomia](https://ohdsi.github.io/Eunomia/) to create a fully runnable example. Eunomia already contains a simple simulated database in CDM format, and is available on CRAN. See the [CohortDiagnostics unit tests](https://github.com/OHDSI/CohortDiagnostics/blob/master/tests/testthat/test-againstEunomia.R) for an example.

SQLite does not support DATE and DATETIME data types, so I've hacked some rules in DatabaseConnector and SqlRender to emulate those. Those hacks are not 100% effective in all situations, so I keep having to add some refinements. In fact there are several important fixes in the SqlRender develop branch you may need to run SCC on Eunomia.

**Comment by ablack3** [comment]
Ok I'll try using Eunomia and the development branch of SqlRender. I thought using Andromeda might be nice for explanation and testing since it would allow me to create the simplest non-trivial example. I'll give Eunomia a shot though.

**Comment by ablack3** [comment]
Sorry this is taking so long! I do have a good start.

**Comment by ablack3** [comment]
Recording some ideas for possible improvements:

- Check that column names are as expected and report error if they are not.
- Automatically assign column names for any CDM event table used as either exposure or outcome table.
- Allow for smoothing of irr estimates to avoid irrs of 0 or Inf when outcome counts are zero.
- Better handling of dates in SQLite (e.g. use days instead of seconds)

**Comment by azimov** [comment]
@ablack3  Do you need any help with this? I make a lot of use of this package so I'm happy to collaborate

**Comment by ablack3** [comment]
Hi @azimov , yes I would love to collaborate. I'll create a pull request with my draft. I have never really used this package so I'm sure you will have a lot of valuable insight to add!
